export const state = () => ({
  list: [
    {
      id: 265186232323,
      number: 1,
      name: 'admin',
      discount: 15,
      vip: 'Gold',
      coinomy: true,
      investor: true,
    },
    {
      id: 265186232324,
      number: 2,
      name: 'admin',
      discount: 15,
      vip: 'Wood',
      coinomy: false,
      investor: false,
    },
    {
      id: 265186232325,
      number: 3,
      name: 'admin',
      discount: 15,
      vip: 'Iron',
      coinomy: true,
      investor: false,
    },
    {
      id: 265186232326,
      number: 4,
      name: 'admin',
      discount: 15,
      vip: 'Bronze',
      coinomy: false,
      investor: true,
    },
    {
      id: 265186232327,
      number: 5,
      name: 'admin',
      discount: 15,
      vip: 'Steel',
      coinomy: false,
      investor: true,
    }, {
      id: 265186232328,
      number: 6,
      name: 'admin',
      discount: 15,
      vip: 'Silver',
      coinomy: false,
      investor: true,
    },
    {
      id: 265186232329,
      number: 7,
      name: 'admin',
      discount: 15,
      vip: 'Palladium',
      coinomy: false,
      investor: true,
    },
    {
      id: 265186232330,
      number: 8,
      name: 'admin',
      discount: 15,
      vip: 'Platinum',
      coinomy: false,
      investor: true,
    },
    {
      id: 265186232331,
      number: 9,
      name: 'admin',
      discount: 15,
      vip: 'Emerald',
      coinomy: true,
      investor: true,
    },
    {
      id: 265186232332,
      number: 10,
      name: 'admin',
      discount: 15,
      vip: 'Sapphire',
      coinomy: false,
      investor: true,
    },
    {
      id: 265186232333,
      number: 11,
      name: 'admin',
      discount: 15,
      vip: 'Gold',
      coinomy: true,
      investor: true,
    },
  ],
});

export const getters = {
  getGroupsList: (s) => s.list,
};
